In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import pickle
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
gender_encoder=LabelEncoder()
data['Gender']=gender_encoder.fit_transform(data['Gender'])
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France       0   42   
1             2    15647311       Hill          608     Spain       0   41   
2             3    15619304       Onio          502    France       0   42   
3             4    15701354       Boni          699    France       0   39   
4             5    15737888   Mitchell          850     Spain       0   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France       1   39   
9996       9997    15569892  Johnstone          516    France       1   35   
9997       9998    15584532        Liu          709    France       0   36   
9998       9999    15682355  Sabbatini          772   Germany       1   42   
9999      10000    15628319     Walker          792    France       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
with open('onehot_encoder_geo.pkl','rb') as file:
    geo_encoder=pickle.load(file)


In [ ]:
geo_labels=geo_encoder.transform(data[['Geography']]).toarray()
geo_labels

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [27]:
geo_labels_df=pd.DataFrame(geo_labels,columns=geo_encoder.get_feature_names_out(['Geography']))
geo_labels_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [24]:
geo_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [18]:
#model=keras.models.load_model('model.h5')

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)

with open('scalar.pkl','rb') as file:
    scalar=pickle.load(file)


In [33]:
data=pd.concat([data.drop('Geography',axis=1),geo_labels_df],axis=1)

In [48]:
data

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1               1.0   
1                  1        112542.58       0               0.0   
2                  0        113931.57       1               1.0   
3                  0         93826.63       0               1.0   
4                  1         79084.10       0               0.0   
...              ...              ...     ...               ...   
9995               0         96270.64       0               1.0   
9996               1        101699.77       0               1.0   
9997               1         42085.58       1               1.0   
9998               0         92888.52       1               0.0   
9999               0         38190.78       0               1.0   

      Geography_Germany  Geography_Spain  
0                   0.0              0.0  
1                   0.0              1.0  
2                   0.0              0.0  
3                   0.0              0.0  
4                   0.0              1.0  
...                 ...              ...  
9995                0.0              0.0  
9996                0.0              0.0  
9997                0.0              0.0  
9998                1.0              0.0  
9999                0.0              0.0  

[10000 rows x 13 columns]

In [39]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [40]:
x=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [41]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [42]:
xtrain=scalar.fit_transform(xtrain)
xtest=scalar.transform(xtest)

In [44]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorboard


In [46]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(xtrain.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

In [54]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                832       
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [59]:
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
TensorBoard_callbacks=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [ ]:
early_stopping_callbacks=EarlyStopping(patience=10,monitor='val_loss',restore_best_weights=True)

In [65]:
history=model.fit(
    xtrain,ytrain,
    validation_data=(xtest,ytest),
    epochs=50,
    callbacks=[early_stopping_callbacks,TensorBoard_callbacks]
)

Epoch 1/50
250/250 [==============================] - 3s 9ms/step - loss: 49545.0977 - mae: 49545.0977 - val_loss: 50262.3945 - val_mae: 50262.3945
Epoch 2/50
250/250 [==============================] - 1s 3ms/step - loss: 49536.5273 - mae: 49536.5273 - val_loss: 50267.6523 - val_mae: 50267.6523
Epoch 3/50
250/250 [==============================] - 1s 3ms/step - loss: 49529.3789 - mae: 49529.3789 - val_loss: 50274.3516 - val_mae: 50274.3516
Epoch 4/50
250/250 [==============================] - 1s 4ms/step - loss: 49522.8477 - mae: 49522.8477 - val_loss: 50257.9570 - val_mae: 50257.9570
Epoch 5/50
250/250 [==============================] - 1s 3ms/step - loss: 49514.9922 - mae: 49514.9922 - val_loss: 50260.2539 - val_mae: 50260.2539
Epoch 6/50
250/250 [==============================] - 1s 3ms/step - loss: 49509.6172 - mae: 49509.6172 - val_loss: 50260.5195 - val_mae: 50260.5195
Epoch 7/50
250/250 [==============================] - 1s 3ms/step - loss: 49503.7461 - mae: 49503.7461 - val_los

In [66]:
%reload_ext tensorboard

In [70]:
%tensorboard --logdir regressionlogs/fit/

ERROR: Timed out waiting for TensorBoard to start. It may still be running as pid 46256.

In [68]:
!kill 45766

In [73]:
with open('scaled_Data.pkl','rb') as file:
    input_scaled=pickle.load(file)

In [74]:
input_scaled

array([[-0.53598516, -1.09499335,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [75]:
## PRedict churn
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 1s 1s/step


array([[92898.21]], dtype=float32)

In [76]:
prediction_proba = prediction[0][0]
prediction_proba

92898.21